server:
  port: 0
spring:
  application:
    name: API-GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: room-reservation-service
          uri: http://localhost:9090
          predicates:
            - Path=/roomReservations/**
          filters:
            - name: Logging
              args:
                tag: room-reservation-service
