server:
  port: 9095
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: room-reservation-service
          uri: lb://room-reservation-service
          predicates:
            - Path=/roomReservations/**
          filters:
            - name: Logging
              args:
                tag: room-reservation-service
        - id: config-server
          uri: lb://config-server
          predicates:
            - Path=/config-server/**
          filters:
            - StripPrefix=1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
