server:
  port: 9095
spring:
  cloud:
    gateway:
      routes:
        - id: room-reservation-service
          uri: lb://room-reservation-service
          predicates:
            - Path=/roomReservations/**
          filters:
            - name: Logging
              args:
                tag: room-reservation-service
        - id: config-server
          uri: http://localhost:8088
          predicates:
            - Path=/config-server/**
          filters:
            - StripPrefix=1
