server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/payment_service
    username: postgres
    password: postgres

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    url: jdbc:postgresql://localhost:5433/payment_service
    user: postgres
    password: postgres

  # Kafka configuration (currently commented out)
  # kafka:
  #   bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
  #   consumer:
  #     group-id: room-payment-consumer
  #     auto-offset-reset: earliest
  #     key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  #     value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
  #   producer:
  #     key-serializer: org.apache.kafka.common.serialization.StringSerializer
  #     value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
